### ISSUE TITLE
Responsive - certaines pages de topic continuent de "remonter" toutes seules lors de la lecture

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/themeForum#5]
Je n'ai pas vraiment réussi à déterminer de comportement type qui fait que ce bug continue.
Tout ce que j'ai pu remarquer c'est que :
- ça le fait sur certains topics, pas sur tous (par contre je ne me rappelle plus de si ce sont toujours les mêmes topics ou non),
- lors de la lecture uniquement
- une fois qu'on a agi sur la page (fait un commentaire, liké un message), la remontée folle s'arrête.

**Comment by elpiolito** [comment]
Je pense que je vois mais je ne vais pas pouvoir y faire grande chose je pense. 
Pour moi, c'est le chargement des images : la page est d'abord chargée sans les images puis elles sont ajoutées au fur et à mesure. Comme elles sont grandes, elle redimensionnent les posts au fur et à mesure qu'elle apparaissent donc t'as l'impression que ça srcolle.

Si tu attends genre quelques secondes sans rien faire, ça se stoppe tout seul ?

**Comment by MarieOphelie** [comment]
J'ai remarqué depuis que ça le fait aussi sur des pages sans images, par exemple quand tu es sur la page d'un sous-forum (dans "Le bar" par exemple, là où est affichée la liste des topics).
Si j'attends quelques secondes sans rien faire, ça se stoppe une fois que c'est remonté tout en haut mdr, mais si je scrolle ça recommence.

Avant ça le faisait sur la page d'accueil et maintenant ça ne le fait plus ; tu avais fait comment pour fixer le problème ?

**Comment by elpiolito** [comment]
Je n'ai absolument rien fait : des fois, ça se résous magiquement tout seul :)

Mais c'est bizarre quand même, moi j'ai jamais rencontré le soucis (enfin je ne crois pas). Je suppose que tu utilises le navigateur de Satan ?
Si c'est pas les images, c'est peut-être le header alors, j'ai vu qu'il avait une tendance à se positionner au dessus de certains messages parfois, faudrait que je regarde.

**Comment by MarieOphelie** [comment]
_"Je suppose que tu utilises le navigateur de Satan ?"_
Mdr à ton avis ? Tu sais bien que les péchés et moi, on ne fait qu'un ! :p (oui, j'utilise Chrome)

**Comment by GalaxSerieAll** [comment]
Anto a le même problème sur le forum aussi, sur portable, avec Firefox.

https://forum.serieall.fr/viewtopic.php?p=928#p928

**Comment by elpiolito** [comment]
Oui, j'ai aussi le soucis depuis la dernière mise a jour de Firefox, je vois mieux le soucis et j'arrive a reproduire. Quand je pourrai, je corrigerai

**Comment by elpiolito** [comment]
Corrigé avec commit 3a9a21578abb44f40f4e0fa5b79287aecfdbc8d6
